groupName: acme.blackhouse.dev

certManager:
  namespace: cert-manager
  serviceAccountName: cert-manager

image:
  repository:  quay.io/neogeneva/cert-manager-webhook-godaddy
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 443

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}