groupName: acme.blackhouse.dev

certManager:
  namespace: cert-manager
  serviceAccountName: cert-manager

image:
  repository: r.cfcr.io/neogeneva/neogeneva/cert-manager-webhook-godaddy
  tag: 0.0.1
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 443

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}